<?php

namespace ContainerVFr535C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpressionServiceInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Helper\SymfonyExpression\ExpressionServiceInterface' shared autowired service.
     *
     * @return \Pimcore\Helper\SymfonyExpression\ExpressionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Helper/SymfonyExpression/ExpressionServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Helper/SymfonyExpression/ExpressionService.php';

        return $container->services['Pimcore\\Helper\\SymfonyExpression\\ExpressionServiceInterface'] = new \Pimcore\Helper\SymfonyExpression\ExpressionService();
    }
}
