<?php

namespace ContainerVFr535C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGridHelperServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\AdminBundle\Helper\GridHelperService' shared autowired service.
     *
     * @return \Pimcore\Bundle\AdminBundle\Helper\GridHelperService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/admin-ui-classic-bundle/src/Helper/GridHelperService.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['Pimcore\\Bundle\\AdminBundle\\Helper\\GridHelperService'])) {
            return $container->privates['Pimcore\\Bundle\\AdminBundle\\Helper\\GridHelperService'];
        }

        return $container->privates['Pimcore\\Bundle\\AdminBundle\\Helper\\GridHelperService'] = new \Pimcore\Bundle\AdminBundle\Helper\GridHelperService($a);
    }
}
