doctrine:
    dbal: { connections: { default: { host: localhost, port: 3306, user: root, password: root, dbname: pimcore_project, mapping_types: { enum: string, bit: boolean }, server_version: 8.0.39-0ubuntu0.24.04.1 } } }
